### ISSUE TITLE
Lag Function Calling

### ISSUE THREAD

**Issue by stoneeast** [ninjapapa/RuiBu#1]
Created a hard-coded version lag GDO in https://github.com/ninjapapa/RuiBu/blob/master/src/main/scala/org/ruibu/estore/profiling/OutStockCal.scala. Tried several ways to call it to retain DOC_DATE and all failed. May need help to have a review.

**Comment by ninjapapa** [comment]
Just implemented smvLag in SMV package. Client code will look like:
```scala
    val res = srdd.smvGroupBy("k").runAgg("t")(
      $"k",
      $"t",
      $"v",
      $"v".smvLag(1) as "v_lag"
    ).selectPlus($"v" - $v_lag" as "v_diff")
```

Please note, you have to use selectPlus (or select) after runAgg to do calculation on "v_lag". runAgg itself does not support using the lag result directly. Another caveat is documented on https://github.com/TresAmigosSD/SMV/issues/128

If you think the better convention should be assign "null" to the first record, I will make the change on ```smvLag```'s definition. 

Also I haven't tested on real data. Please keep an eye on the results. There could be potential issues, especially when we do ```smvLag(N)``` when N>1.

**Comment by stoneeast** [comment]
Thanks and it looks good. I test it in real data with N > 1. Script is added.
